const api = 'api/';

const v1 = `${api}v1/`;
const v2 = `${api}v2/`;

export default {
	login: `${api}login`,
	register: `${v2}user/register`,
	resetPassword: `${api}forgot-password`,
	checkEmail: `${v2}user/checkEmail`,
	validateInvite: `${v2}user/validateInvite`,
	acceptInvite: `${v2}user/acceptInvite`,
	wod: `${v1}wod`,
	attendStatus: `${v1}fitbox/leaderboard/attend-sessions`,
	scoreMissingWods: `${v1}fitbox/leaderboard/wod-attended`,
	attendanceReport: `${v1}fitbox/leaderboard/attendance-report`,
	attendSession: `${v1}fitbox/leaderboard/add-attendance`,
	updateAttendance: `${v1}fitbox/leaderboard/update-attendance`,
	scheduleList: `${v1}schedulelist`,
	scheduleDetail: `${v1}schedule-detail`,
	completedWods: `${v1}fitbox/leaderboard/wod-schedule`,
	sectionDetail: `${v1}fitbox/leaderboard/section-detail`,
	addScore: `${v1}fitbox/leaderboard/add-score`,
	getScore: `${v1}fitbox/leaderboard/get-scores`,
	movements: `${v1}fitbox/leaderboard/movements`,
	addWodScore: `${v1}fitbox/user/wod/add-score`,
	removeWodScore: `${v1}fitbox/user/wod/remove-score`,
	updateWodScore: `${v1}fitbox/user/wod/update-score`,
	workouts: `${v1}fitbox/leaderboard/workouts`,
	workoutsPastPerformance: `${v1}past-performance`,
	scoringtypes: `${v1}fitbox/scoring-types`,
	userAddScore: `${v1}fitbox/user/movement/add-score`,
	userDeleteScore: `${v1}fitbox/user/movement/remove-score`,
	userUpdateScore: `${v1}fitbox/user/movement/update-score`,
	getPastPerformance: `${v1}fitbox/user/get-past-performance`,
	userMovements: `${v1}fitbox/user/movements`,
	conversationList: `${v1}message/conversations`,
	conversationArchivedList: `${v1}message/conversations/trashed`,
	conversationMessages: `${v1}message/conversation`,
	checkConversationReplyStatus: `${v1}message/disable-reply-status`,
	sendConversationMessage: `${v1}message/create`,
	deleteConversation: `${v1}message/conversations`,
	deleteConversationMessage: `${v1}message`,
	contacts: `${v1}message/contacts`,
	userHealthInfo: `${v1}get-health-details`,
	userProfileImage: `${v1}user/profile/update-photo`,
	userProfile: `${v1}user/profile`,
	userProfileUpdate: `${v1}user/update`,
	getWhatsNew: `${v1}fitbox/new-features`,
	viewWhatsNew: `${v1}fitbox/user-viewed-new-features`,
	getUserGyms: `${v1}user/allgyms`,
	getGymInfo: `${v1}user/gym`,
	getGymInfoV2: `${v2}user/gym`,
	fitboxGallery: `${v1}media`,
	wellness: `${v1}wellness-new`,
	reportCategories: `${v1}reporting/categories`,
	reports: `${v1}reporting/reports`,
	leaderboards: `${v1}fitbox/leaderboard`,
	eula: `${v1}get-eula`,
	acceptEula: `${v1}get-accept-eula`,
	waiver: `${v1}waiver/get`,
	acceptWaiver: `${v1}accept-waiver`,
	acceptedWaivers: `${v1}waiver/get-user`,
	acceptBillingAgreement: `${v1}accept-billing-agreement`,
	saveHealthInfo: `${v1}save-health-info`,
	stripe: `${v1}stripe/`,
	saveCard: `${v1}stripe/save-payment-info`,
	setupPaymentIntent: `${v1}stripe/setupIntent`,
	getPaymentInfo: `${v1}user/payment/details`,
	getPaymentMethod: `${v1}stripe/getPaymentMethod`,
	confirmSetupIntent: `${v1}stripe/confirmSetupIntent`,
	joinWaitlist: `${v1}waitlist/join`,
	cancelWaitlist: `${v1}waitlist/cancel`,
	getScoreDetails: `${v1}get-score-details`,
	commentScore: `${v1}post-score-comment`,
	getScoreComments: `${v1}class-leaderboard-comments`,
	applauseScore: `${v1}applause-leaderboard-score`,
	getScoreApplauses: `${v1}class-leaderboard-applauses`,
	getClassLeaderboard: `${v1}class-leaderboard`,
	gymClasses: `${v1}fitbox/leaderboard/all-gym-class`,
	gymVenues: `${v1}gym/venues`,
	nextSessions: `${v1}fitbox/leaderboard/next-three-sessions`,
	bookedSessions: `${v1}fitbox/leaderboard/all-booked-sessions`,
	subscriptionSave: `${v1}subscription/save`,
	subscriptionProducts: `${v1}products-after-signup`,
	userSubscriptionProducts: `${v1}products-existing-users`,
	subscriptionInfo: `${v1}subscription/lists`,
	subscriptionDetails: `${v1}subscription/details`,
	toggleEmailNotifications: `${v1}user/subscription/notification`,
	childInfo: `${v1}user/child`,
	parentInfo: `${v1}user/parent`,
	switchAccount: `${v1}user/switch`,
	classFilters: `${v1}classFilters`,
	PushNotificationService:
		'https://fitbox-stg-microservices.azurewebsites.net/api/NotificationService?code=/W0YnAVNdmeGd/gcnAbvIMQqhcpTpiKIs0Qk696AfcAG5EeD5Bg5/Q==',
	// 'https://fitbox-dev-microservices.azurewebsites.net/api/NotificationService?code=sYC9PuVtRl8udPnN8LQTzF/gX2YtX0OltS6xX3bQCAp1ZH0Mg3FknQ==',
};
