import { z } from 'zod';

export const SubscriptionSchema = z.object({
	expiration_date: z.string().nullable(),
	expiration_interval: z.number(),
	expiration_interval_unit: z.string(),
	first_billing_date: z.string(),
	id: z.number(),
	name: z.string(),
	description: z.string().nullable(),
	payment_gateway: z.string().nullable(),
	price_in_cents: z.number(),
	recurring_interval: z.number(),
	recurring_interval_unit: z.string(),
	sessions_count: z.number().nullable(),
	sessions_limit: z.number().nullable(),
	sessions_limit_frequency: z.string().nullable(),
	set_up_price_in_cents: z.number(),
	start_date: z.string(),
	status: z.string(),
	trial_price_in_cents: z.number(),
	type: z.string().optional(),
});

export type SubscriptionType = z.infer<typeof SubscriptionSchema>;

export const TransactionsSchema = z.object({
	amount: z.number(),
	calculated_fee: z.number(),
	created_at: z.string(),
	id: z.number(),
	name: z.string(),
});

export type TransactionsType = z.infer<typeof TransactionsSchema>;

export const SubscriptionDetailsSchema = z.object({
	apply_transaction_fees_to_member: z.number(),
	cancellation_date: z.string().nullable(),
	description: z.string(),
	expiration_interval: z.number(),
	expiration_interval_unit: z.string(),
	first_billing_date: z.string(),
	id: z.number(),
	name: z.string(),
	next_payment_date: z.string().nullable(),
	price_in_cents: z.number(),
	recurring_interval: z.number(),
	recurring_interval_unit: z.string(),
	sessions_count: z.number().nullable(),
	sessions_limit: z.number().nullable(),
	sessions_limit_frequency: z.string(),
	set_up_price_in_cents: z.number(),
	suspended_begin_date: z.string().nullable(),
	suspended_until_date: z.string().nullable(),
	trial_price_in_cents: z.number(),
	type: z.string(),
});

export type SubscriptionDetailsType = z.infer<typeof SubscriptionDetailsSchema>;

export const UserSubscriptionProductsSchema = z.object({
	apply_transaction_fees_to_member: z.number(),
	archived: z.number(),
	context_id: z.number(),
	created_at: z.string(),
	description: z.string(),
	expiration_interval: z.number(),
	expiration_interval_unit: z.string(),
	id: z.number(),
	name: z.string(),
	notify_on_low_count: z.number(),
	payment_gateway: z.string().nullable(),
	price_in_cents: z.number(),
	recurring_interval: z.number(),
	recurring_interval_unit: z.string(),
	reference: z.string(),
	remote_id: z.string(),
	return_params: z.string(),
	return_url: z.string(),
	sessions_limit: z.number().nullable(),
	sessions_limit_frequency: z.string().nullable(),
	set_up_price_in_cents: z.number(),
	show_after_signup: z.number(),
	show_existing_users: z.number(),
	subscription_available_on_mobile: z.number(),
	trial_interval: z.number(),
	trial_interval_unit: z.string(),
	trial_price_in_cents: z.number(),
	trial_type: z.string(),
	type: z.string(),
	updated_at: z.string(),
});

export type UserSubscriptionProductsType = z.infer<
	typeof UserSubscriptionProductsSchema
>;

export const SubscriptionSaveMemberSchema = z.object({
	activated_at: z.string(),
	added_via_prospect: z.number(),
	address1: z.string(),
	address2: z.string(),
	allow_skip_payment_form: z.string(),
	archived_at: z.string(),
	billing_agreement_accepted: z.number(),
	can_cancel_membership: z.number(),
	city: z.string(),
	completed_profile: z.number(),
	contact_phone: z.string(),
	country: z.string(),
	created_at: z.string(),
	created_by: z.number(),
	current_weight: z.number(),
	date_format: z.string(),
	default_team_id: z.number(),
	deleted_at: z.string().nullable(),
	dob: z.string(),
	email: z.string(),
	email_training_notifications: z.number(),
	emergency_contact_name: z.string(),
	emergency_contact_number: z.string(),
	eula_accepted: z.number(),
	face_id: z.null().optional(),
	faceme_password: z.null().optional(),
	firstname: z.string(),
	full_training_date: z.null().optional(),
	gender: z.string(),
	grade: z.number(),
	guid: z.string(),
	has_credit_card_details: z.number(),
	has_direct_debit_details: z.number(),
	has_viewed_new_features: z.number(),
	height: z.number(),
	id: z.number(),
	is_cancelled_membership: z.number(),
	is_child: z.number(),
	is_gym_waver_accepted: z.number(),
	is_health_captured: z.number(),
	last_login: z.string(),
	lastname: z.string(),
	level_changed_at: z.null().optional(),
	locale: z.null().optional(),
	meta_financial: z.string(),
	mobile_number: z.string(),
	notes: z.string(),
	notify_email_subscription: z.number(),
	parent_id: z.number(),
	personal_quota: z.number(),
	postcode: z.string(),
	profile_image: z.string(),
	remember_groupid: z.null().optional(),
	remember_id: z.number(),
	remember_token: z.string(),
	remember_type: z.string(),
	secondary_email: z.string(),
	show_billing_form: z.number(),
	show_payment_form: z.number(),
	state: z.string(),
	status_description: z.null().optional(),
	status_summary_title: z.null().optional(),
	stripe_account_id: z.null().optional(),
	stripe_source_id: z.null().optional(),
	timezone: z.string(),
	training_level: z.number(),
	updated_at: z.string(),
	updated_by: z.number(),
	user_availability: z.number(),
	user_availability_date: z.null().optional(),
	validic_access_token: z.string(),
	validic_user_id: z.string(),
	weight_unit: z.string(),
	zendesk_user_id: z.null().optional(),
});

export const SubscriptionSaveSchema = z.object({
	context_id: z.number(),
	created_at: z.string(),
	current_period_start_date: z.string(),
	customer_id: z.number(),
	id: z.number(),
	member: SubscriptionSaveMemberSchema,
	payment_method: z.string(),
	product: UserSubscriptionProductsSchema,
	product_id: z.number(),
	remote_customer_id: z.string(),
	remote_id: z.string(),
	remote_product_id: z.string(),
	sessions_count: z.number().nullable(),
	sessions_count_last_reset: z.object({
		date: z.string(),
		timezone: z.string(),
		timezone_type: z.number(),
	}),
	start_date: z.string(),
	status: z.string(),
	updated_at: z.string(),
});

export const SaveSubscriptionPayloadSchema = z.object({
	customer_id: z.number(),
	product_id: z.number(),
	product_type: z.string(),
	first_billing_date: z.string(),
	recurringStartDate: z.string(),
	price_in_cents: z.number(),
	set_up_price_in_cents: z.number(),
	trial_price_in_cents: z.number(),
	start_date: z.string(),
	from_signup: z.boolean(),
});

export type SaveSubscriptionPayloadType = z.infer<
	typeof SaveSubscriptionPayloadSchema
>;
