import { z } from 'zod';
import { boolOrOneZero } from './common';

export const UserSchema = z.object({
	user_id: z.number(),
	first_name: z.string(),
	last_name: z.string(),
	face_id: z.null().optional(),
	email: z.string().email(),
	contact_phone: z.string(),
	dob: z.object({
		date: z.string(),
		timezone_type: z.literal(3),
		timezone: z.string(),
	}),
	height: z.number(),
	current_weight: z.number(),
	gender: z.enum(['Male', 'Female', 'Other']),
	show_subscription_from: z.boolean().optional(),
	show_payment_form: boolOrOneZero,
	show_billing_form: boolOrOneZero,
	billing_agreement_accepted: boolOrOneZero,
	device_type: z.null().optional(),
	push_token: z.string().nullable(),
	profile_image: z.string().url(),
	gym_logo: z.string().url(),
	banner_image: z.string().url(),
	unread_item: z.number(),
	eula_accepted: boolOrOneZero,
	has_waived_subscriptions: boolOrOneZero,
	has_paid_subscriptions: boolOrOneZero,
	waiver_accepted: boolOrOneZero,
	has_payment_details: z.union([
		z.boolean(),
		z.string(),
		z.literal(1),
		z.literal(0),
	]),
	is_staff: boolOrOneZero,
	notice: z.string(),
	last_login: z.string(),
	is_health_captured: boolOrOneZero,
	allow_leaderboards: boolOrOneZero,
	allow_leaderboards_comment: boolOrOneZero,
	is_parent: boolOrOneZero,
	is_child: boolOrOneZero,
	parent_id: z.number(),
	onboarding_gym_ids: z.array(z.number()),
	emergency_contact_name: z.string(),
	emergency_contact_number: z.string(),
});

export const UserProfileSchema = z.object({
	address1: z.string().optional(),
	address2: z.string().optional(),
	city: z.string().optional(),
	contact_phone: z.string(),
	current_weight: z.number(),
	dob: z.object({
		date: z.string(),
		timezone: z.string(),
		timezone_type: z.number(),
	}),
	email: z.string(),
	emergency_contact_name: z.string().optional(),
	emergency_contact_number: z.string().optional(),
	eula_accepted: z.number().optional(),
	face_id: z.any().optional(),
	first_name: z.string(),
	gender: z.string(),
	has_payment_details: z.number().optional(),
	height: z.number(),
	last_name: z.string(),
	postcode: z.string().optional(),
	profile_image: z.string(),
	state: z.string().optional(),
	timezone: z.string(),
	user_id: z.number(),
	waiver_accepted: z.number().optional(),
});

export type UserProfileType = z.infer<typeof UserProfileSchema>;
export type UserSchemaType = z.infer<typeof UserSchema>;
