import { z } from 'zod';
import { boolOrOneZero } from './common';

export const userSchema = z.object({
	user_id: z.number(),
	first_name: z.string(),
	last_name: z.string(),
	face_id: z.null().optional(),
	email: z.string().email(),
	contact_phone: z.string(),
	dob: z.object({
		date: z.string(),
		timezone_type: z.literal(3),
		timezone: z.string(),
	}),
	height: z.number(),
	current_weight: z.number(),
	gender: z.enum(['Male', 'Female', 'Other']),
	show_payment_form: boolOrOneZero,
	show_billing_form: boolOrOneZero,
	billing_agreement_accepted: boolOrOneZero,
	device_type: z.null().optional(),
	push_token: z.string(),
	profile_image: z.string().url(),
	gym_logo: z.string().url(),
	banner_image: z.string().url(),
	unread_item: z.number(),
	eula_accepted: boolOrOneZero,
	has_waived_subscriptions: boolOrOneZero,
	has_paid_subscriptions: boolOrOneZero,
	waiver_accepted: boolOrOneZero,
	has_payment_details: boolOrOneZero,
	is_staff: boolOrOneZero,
	notice: z.string(),
	last_login: z.string(),
	is_health_captured: boolOrOneZero,
	allow_leaderboards: boolOrOneZero,
	allow_leaderboards_comment: boolOrOneZero,
	is_parent: boolOrOneZero,
	is_child: boolOrOneZero,
	parent_id: z.number(),
	onboarding_gym_ids: z.array(z.number()),
	emergency_contact_name: z.string(),
	emergency_contact_number: z.string(),
});
